// ─── Central Question Bank ─────────────────────────────────────────────────
// Storage key: rqa_question_bank
// Question types: 'mcq' | 'match' | 'image'
// Categories: 'robotics' | 'chemistry' | 'physics' | 'mathematics'

const QB_KEY = 'rqa_question_bank';

// ─── Default Robotics Questions (30) ──────────────────────────────────────
export const DEFAULT_ROBOTICS = [
  { id:'rob001', category:'robotics', type:'mcq', difficulty:'easy', status:'active',
    text:'Which of the following is NOT a core component of a robot?',
    options:['Actuator','Sensor','Compiler','Controller'], correct:2,
    explanation:'A compiler is a software tool, not a hardware component of a robot.' },
  { id:'rob002', category:'robotics', type:'mcq', difficulty:'easy', status:'active',
    text:'What does the Sense-Think-Act cycle represent in robotics?',
    options:['A power management routine','A startup sequence','A continuous real-time loop for robot decision-making','A manual override protocol'],
    correct:2, explanation:'The Sense-Think-Act cycle is how robots continuously interact with their environment.' },
  { id:'rob003', category:'robotics', type:'mcq', difficulty:'easy', status:'active',
    text:'Which component of a robot produces physical movement?',
    options:['Sensor','Actuator','Controller','Power supply'], correct:1,
    explanation:'Actuators (motors, pistons, etc.) convert energy into physical movement.' },
  { id:'rob004', category:'robotics', type:'mcq', difficulty:'easy', status:'active',
    text:'What does ROS stand for in robotics?',
    options:['Robotic Output System','Robot Operating System','Reactive Object Sensing','Remote Operations Software'],
    correct:1, explanation:'ROS (Robot Operating System) is open-source middleware for building robot applications.' },
  { id:'rob005', category:'robotics', type:'mcq', difficulty:'easy', status:'active',
    text:'Which programming language is most common in embedded robotics systems?',
    options:['JavaScript','Python','C / C++','Scratch'], correct:2,
    explanation:'C/C++ is preferred for embedded systems due to performance and hardware control.' },
  { id:'rob006', category:'robotics', type:'mcq', difficulty:'easy', status:'active',
    text:'What type of robot is typically used in car manufacturing for welding?',
    options:['Service robot','Industrial robot','Medical robot','Educational robot'], correct:1,
    explanation:'Industrial robots are fixed-arm robots used for welding, painting, and assembly.' },
  { id:'rob007', category:'robotics', type:'mcq', difficulty:'easy', status:'active',
    text:'What does an ultrasonic sensor measure?',
    options:['Temperature','Light intensity','Distance using sound waves','Magnetic field'],
    correct:2, explanation:'Ultrasonic sensors emit sound waves and measure the time for the echo to return.' },
  { id:'rob008', category:'robotics', type:'mcq', difficulty:'easy', status:'active',
    text:"NASA's Mars rover Perseverance is an example of which robot category?",
    options:['Industrial robot','Autonomous mobile robot','Service robot','Surgical robot'],
    correct:1, explanation:'Mars rovers navigate autonomously, classifying them as autonomous mobile robots (AMRs).' },
  { id:'rob009', category:'robotics', type:'mcq', difficulty:'medium', status:'active',
    text:'Which motor type is best for precise angular position control?',
    options:['AC induction motor','Brushless DC motor','Stepper motor','Servo motor'],
    correct:3, explanation:'Servo motors include position feedback (encoder) making them ideal for precise angle control.' },
  { id:'rob010', category:'robotics', type:'mcq', difficulty:'medium', status:'active',
    text:'What does a gyroscope sensor measure in a robot?',
    options:['Distance to objects','Rotational velocity and orientation','Ambient temperature','Electrical current'],
    correct:1, explanation:'Gyroscopes measure angular velocity and help determine the orientation of a robot.' },
  { id:'rob011', category:'robotics', type:'mcq', difficulty:'medium', status:'active',
    text:'In a PID controller, what does the "D" term respond to?',
    options:['Accumulated error over time','Current error value','Rate of change of error','Predicted future error'],
    correct:2, explanation:'The Derivative term responds to how fast the error is changing, dampening oscillations.' },
  { id:'rob012', category:'robotics', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the primary advantage of pneumatic actuators in industrial robots?',
    options:['More precise positioning','High force output with lightweight design','Lower energy consumption','Quieter operation'],
    correct:1, explanation:'Pneumatic actuators use compressed air to deliver high force without heavy motors.' },
  { id:'rob013', category:'robotics', type:'mcq', difficulty:'medium', status:'active',
    text:'A PIR sensor detects:',
    options:['Pressure changes','Infrared radiation from warm bodies','Proximity via ultrasound','Colour wavelengths'],
    correct:1, explanation:'PIR (Passive Infrared) sensors detect heat signatures emitted by living bodies.' },
  { id:'rob014', category:'robotics', type:'mcq', difficulty:'medium', status:'active',
    text:'An encoder converts rotary motion into:',
    options:['Analog voltage signals','Magnetic pulses','Digital pulses for position/speed measurement','Optical wavelengths'],
    correct:2, explanation:'Encoders generate digital pulses as a shaft rotates, measuring speed and position.' },
  { id:'rob015', category:'robotics', type:'mcq', difficulty:'medium', status:'active',
    text:'Which algorithm is widely used for pathfinding in autonomous robots?',
    options:['Bubble sort','A* (A-star)','Binary search','Quick sort'],
    correct:1, explanation:'A* is a popular and efficient graph traversal algorithm used in robot navigation.' },
  { id:'rob016', category:'robotics', type:'mcq', difficulty:'medium', status:'active',
    text:'What does SLAM stand for in robotics navigation?',
    options:['Systematic Location and Mapping','Simultaneous Localisation and Mapping','Sequential Learning and Motion','Sensor-based Landmark Analysis and Monitoring'],
    correct:1, explanation:'SLAM enables a robot to build a map of an unknown environment while tracking its own location.' },
  { id:'rob017', category:'robotics', type:'mcq', difficulty:'medium', status:'active',
    text:'LiDAR sensors work by emitting:',
    options:['Radio waves','Sound pulses','Laser light pulses','Infrared heat beams'],
    correct:2, explanation:'LiDAR (Light Detection and Ranging) emits laser pulses and measures reflection time.' },
  { id:'rob018', category:'robotics', type:'mcq', difficulty:'hard', status:'active',
    text:'Which machine learning technique is most commonly used for robot path planning?',
    options:['Linear regression','Reinforcement learning','K-means clustering','Naive Bayes'],
    correct:1, explanation:'Reinforcement learning trains robots by rewarding correct navigation decisions.' },
  { id:'rob019', category:'robotics', type:'mcq', difficulty:'hard', status:'active',
    text:'What does "degrees of freedom" (DOF) refer to in a robotic arm?',
    options:['Number of sensors attached','Number of independent movements the arm can perform','Maximum payload capacity','Power supply voltage range'],
    correct:1, explanation:'DOF indicates how many independent directions of movement the robot arm can perform.' },
  { id:'rob020', category:'robotics', type:'mcq', difficulty:'hard', status:'active',
    text:'The Kalman Filter is used in robotics primarily for:',
    options:['Image compression','Path optimisation','Sensor fusion to improve state estimation','Motor speed control'],
    correct:2, explanation:'Kalman Filters combine noisy sensor readings to produce optimal state estimates.' },
  { id:'rob021', category:'robotics', type:'mcq', difficulty:'hard', status:'active',
    text:'In deep reinforcement learning for robotics, the "reward function" defines:',
    options:['The physical structure of the robot','Desired behaviour by assigning scores to actions','Sensor calibration parameters','Power consumption limits'],
    correct:1, explanation:'The reward function quantifies how "good" an action is, guiding the learning process.' },
  { id:'rob022', category:'robotics', type:'mcq', difficulty:'hard', status:'active',
    text:'ROS 2 improves over ROS 1 primarily by adding:',
    options:['Better Python support','Real-time capabilities and improved multi-robot support','Lower memory footprint','Easier installation'],
    correct:1, explanation:'ROS 2 uses DDS middleware enabling real-time guarantees and better multi-robot systems.' },
  { id:'rob023', category:'robotics', type:'mcq', difficulty:'hard', status:'active',
    text:'A convolutional neural network (CNN) in robotics vision is primarily used for:',
    options:['Motor control','Image recognition and object detection','Battery management','Sensor calibration'],
    correct:1, explanation:'CNNs excel at visual pattern recognition, making them ideal for robot vision tasks.' },
  { id:'rob024', category:'robotics', type:'mcq', difficulty:'hard', status:'active',
    text:'Swarm robotics is based on the principle of:',
    options:['One powerful central robot controlling many small units','Many simple robots cooperating through local interactions','A cloud server coordinating all robot actions','A single AI brain shared across all units'],
    correct:1, explanation:'Swarm robots mimic natural swarms (ants, bees) where intelligence emerges from simple local rules.' },
  { id:'rob025', category:'robotics', type:'mcq', difficulty:'hard', status:'active',
    text:'Transfer learning in robotics typically involves:',
    options:['Transferring power between battery packs','Applying knowledge from simulation or one task to a new real-world task','Uploading sensor data to the cloud','Copying motor firmware'],
    correct:1, explanation:'Transfer learning reuses trained models to speed up learning in new but related environments.' },
  { id:'rob026', category:'robotics', type:'match', difficulty:'medium', status:'active',
    text:'Match each sensor to its primary measurement:',
    pairs:[
      { left:'Ultrasonic sensor', right:'Distance via sound waves' },
      { left:'Gyroscope',         right:'Rotational velocity / orientation' },
      { left:'Encoder',           right:'Position and speed feedback' },
      { left:'PIR sensor',        right:'Infrared heat from living bodies' },
    ] },
  { id:'rob027', category:'robotics', type:'match', difficulty:'easy', status:'active',
    text:'Match each robot type to its primary application:',
    pairs:[
      { left:'Industrial robot',  right:'Welding and assembly in factories' },
      { left:'Surgical robot',    right:'Minimally invasive medical procedures' },
      { left:'Educational robot', right:'Teaching programming to students' },
      { left:'AMR',               right:'Autonomous warehouse navigation' },
    ] },
  { id:'rob028', category:'robotics', type:'match', difficulty:'hard', status:'active',
    text:'Match each robotics algorithm / technique to its purpose:',
    pairs:[
      { left:'SLAM',              right:'Map environment while tracking position' },
      { left:'Kalman Filter',     right:'Fuse noisy sensor data for accurate estimates' },
      { left:'A* Algorithm',      right:'Find optimal path from start to goal' },
      { left:'PID Controller',    right:'Minimise error between target and actual value' },
    ] },
  { id:'rob029', category:'robotics', type:'match', difficulty:'medium', status:'active',
    text:'Match each actuator to its working principle:',
    pairs:[
      { left:'Servo motor',       right:'Closed-loop position control via feedback' },
      { left:'Stepper motor',     right:'Precise angular steps without feedback' },
      { left:'Pneumatic actuator',right:'Force from compressed air' },
      { left:'Hydraulic actuator',right:'Force from pressurised fluid' },
    ] },
  { id:'rob030', category:'robotics', type:'match', difficulty:'easy', status:'active',
    text:'Match each robotics acronym to its full form:',
    pairs:[
      { left:'ROS',   right:'Robot Operating System' },
      { left:'DOF',   right:'Degrees of Freedom' },
      { left:'SLAM',  right:'Simultaneous Localisation and Mapping' },
      { left:'LiDAR', right:'Light Detection and Ranging' },
    ] },
];

// ─── Default Chemistry Questions (30) ─────────────────────────────────────
export const DEFAULT_CHEMISTRY = [
  { id:'chem001', category:'chemistry', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the chemical symbol for gold?',
    options:['Go','Gd','Au','Ag'], correct:2,
    explanation:'Gold\'s symbol "Au" comes from the Latin "Aurum".' },
  { id:'chem002', category:'chemistry', type:'mcq', difficulty:'easy', status:'active',
    text:'How many protons does a carbon atom have?',
    options:['4','6','8','12'], correct:1,
    explanation:'Carbon has atomic number 6, meaning it has 6 protons.' },
  { id:'chem003', category:'chemistry', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the pH of pure water at 25°C?',
    options:['0','7','10','14'], correct:1,
    explanation:'Pure water is neutral with a pH of exactly 7 at 25°C.' },
  { id:'chem004', category:'chemistry', type:'mcq', difficulty:'easy', status:'active',
    text:'Which gas is produced when an acid reacts with a metal carbonate?',
    options:['Oxygen','Hydrogen','Carbon dioxide','Nitrogen'], correct:2,
    explanation:'Acid + carbonate → salt + water + CO₂.' },
  { id:'chem005', category:'chemistry', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the chemical formula of water?',
    options:['H₂O₂','HO','H₂O','H₃O'], correct:2,
    explanation:'Water consists of two hydrogen atoms bonded to one oxygen atom.' },
  { id:'chem006', category:'chemistry', type:'mcq', difficulty:'easy', status:'active',
    text:'Which element has the highest electronegativity?',
    options:['Oxygen','Nitrogen','Chlorine','Fluorine'], correct:3,
    explanation:'Fluorine has the highest electronegativity value (3.98 on Pauling scale).' },
  { id:'chem007', category:'chemistry', type:'mcq', difficulty:'easy', status:'active',
    text:'What type of bond is formed by sharing electrons between atoms?',
    options:['Ionic bond','Covalent bond','Metallic bond','Hydrogen bond'], correct:1,
    explanation:'Covalent bonds are formed when two atoms share one or more pairs of electrons.' },
  { id:'chem008', category:'chemistry', type:'mcq', difficulty:'easy', status:'active',
    text:'The process by which plants use sunlight to produce glucose is called:',
    options:['Respiration','Combustion','Photosynthesis','Fermentation'], correct:2,
    explanation:'Photosynthesis: 6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂.' },
  { id:'chem009', category:'chemistry', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the oxidation number of sulfur in H₂SO₄?',
    options:['+2','+4','+6','+8'], correct:2,
    explanation:'In H₂SO₄: H is +1 (×2=+2), O is -2 (×4=-8). For neutral: S = +6.' },
  { id:'chem010', category:'chemistry', type:'mcq', difficulty:'medium', status:'active',
    text:'Avogadro\'s number (6.022 × 10²³) represents the number of:',
    options:['Atoms in 1 gram of any element','Particles in one mole of a substance','Molecules per litre of gas at STP','Electrons in a neutral atom'],
    correct:1, explanation:'One mole of any substance contains 6.022 × 10²³ particles (Avogadro\'s constant).' },
  { id:'chem011', category:'chemistry', type:'mcq', difficulty:'medium', status:'active',
    text:'Which type of reaction releases heat energy to the surroundings?',
    options:['Endothermic','Exothermic','Photochemical','Electrochemical'], correct:1,
    explanation:'Exothermic reactions release heat (combustion, neutralisation are examples).' },
  { id:'chem012', category:'chemistry', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the name of the process by which a solid turns directly into a gas?',
    options:['Evaporation','Melting','Sublimation','Condensation'], correct:2,
    explanation:'Sublimation: solid → gas without passing through liquid phase (e.g., dry ice, iodine).' },
  { id:'chem013', category:'chemistry', type:'mcq', difficulty:'medium', status:'active',
    text:'In an electrolysis experiment, at which electrode does oxidation occur?',
    options:['Cathode','Both electrodes','Anode','Neither electrode'], correct:2,
    explanation:'Oxidation (loss of electrons) occurs at the anode; reduction at the cathode.' },
  { id:'chem014', category:'chemistry', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the IUPAC name of CH₃CH₂OH?',
    options:['Methanol','Ethanol','Propanol','Butanol'], correct:1,
    explanation:'CH₃CH₂OH is a 2-carbon alcohol, so its IUPAC name is ethanol.' },
  { id:'chem015', category:'chemistry', type:'mcq', difficulty:'medium', status:'active',
    text:'Which catalyst is used in the Haber process for manufacturing ammonia?',
    options:['Platinum','Vanadium pentoxide','Iron','Nickel'], correct:2,
    explanation:'The Haber process uses an iron catalyst: N₂ + 3H₂ ⇌ 2NH₃.' },
  { id:'chem016', category:'chemistry', type:'mcq', difficulty:'medium', status:'active',
    text:'The electron configuration of sodium (Na, atomic number 11) is:',
    options:['2,8,3','2,9','2,8,1','3,8'], correct:2,
    explanation:'Na has 11 electrons arranged as 2 in K shell, 8 in L shell, 1 in M shell.' },
  { id:'chem017', category:'chemistry', type:'mcq', difficulty:'medium', status:'active',
    text:'What type of isomers have the same molecular formula but different structural formulae?',
    options:['Stereo isomers','Structural isomers','Optical isomers','Geometric isomers'], correct:1,
    explanation:'Structural (constitutional) isomers share the molecular formula but differ in connectivity.' },
  { id:'chem018', category:'chemistry', type:'mcq', difficulty:'hard', status:'active',
    text:'Le Chatelier\'s principle states that if a system at equilibrium is disturbed, it will:',
    options:['Reach a new equilibrium with higher temperature','Shift to counteract the disturbance and restore equilibrium','Stop reacting until conditions normalise','Always favour the forward reaction'],
    correct:1, explanation:'Le Chatelier\'s principle: the system shifts to oppose the change applied to it.' },
  { id:'chem019', category:'chemistry', type:'mcq', difficulty:'hard', status:'active',
    text:'Which quantum number describes the orientation of an orbital in space?',
    options:['Principal quantum number (n)','Azimuthal quantum number (l)','Magnetic quantum number (mₗ)','Spin quantum number (mₛ)'],
    correct:2, explanation:'The magnetic quantum number (mₗ) specifies the orbital\'s orientation in a magnetic field.' },
  { id:'chem020', category:'chemistry', type:'mcq', difficulty:'hard', status:'active',
    text:'What is the hybridisation of carbon in ethyne (C₂H₂)?',
    options:['sp³','sp²','sp','sp³d'], correct:2,
    explanation:'In C₂H₂ (acetylene), each carbon forms 2 sigma bonds → sp hybridisation with a triple bond.' },
  { id:'chem021', category:'chemistry', type:'mcq', difficulty:'hard', status:'active',
    text:'The half-life of a radioactive isotope is 5 years. What fraction remains after 15 years?',
    options:['1/2','1/4','1/8','1/16'], correct:2,
    explanation:'15 years = 3 half-lives. Fraction remaining = (1/2)³ = 1/8.' },
  { id:'chem022', category:'chemistry', type:'mcq', difficulty:'hard', status:'active',
    text:'Buffer solutions resist changes in pH because they contain:',
    options:['Strong acid and strong base','Weak acid and its conjugate base','Salt of a strong acid','Pure distilled water'],
    correct:1, explanation:'A buffer consists of a weak acid and its conjugate base (or weak base + conjugate acid).' },
  { id:'chem023', category:'chemistry', type:'mcq', difficulty:'hard', status:'active',
    text:'Which type of reaction is: CH₂=CH₂ + H₂ → CH₃CH₃?',
    options:['Elimination','Substitution','Addition','Condensation'], correct:2,
    explanation:'Addition reactions occur when molecules add across a double or triple bond.' },
  { id:'chem024', category:'chemistry', type:'mcq', difficulty:'hard', status:'active',
    text:'The Nernst equation is used to calculate:',
    options:['Rate of a chemical reaction','Cell potential under non-standard conditions','Activation energy of a reaction','Equilibrium constant'],
    correct:1, explanation:'The Nernst equation: E = E° - (RT/nF)lnQ, gives cell potential at any concentration.' },
  { id:'chem025', category:'chemistry', type:'mcq', difficulty:'hard', status:'active',
    text:'What does the term "chiral" refer to in organic chemistry?',
    options:['A molecule with a ring structure','A molecule non-superimposable on its mirror image','A molecule with only single bonds','A molecule that absorbs UV light'],
    correct:1, explanation:'Chiral molecules (like amino acids) have a non-superimposable mirror image (enantiomers).' },
  { id:'chem026', category:'chemistry', type:'match', difficulty:'easy', status:'active',
    text:'Match each element symbol to its element name:',
    pairs:[
      { left:'Au', right:'Gold' },
      { left:'Fe', right:'Iron' },
      { left:'Na', right:'Sodium' },
      { left:'K',  right:'Potassium' },
    ] },
  { id:'chem027', category:'chemistry', type:'match', difficulty:'medium', status:'active',
    text:'Match each acid to its common name:',
    pairs:[
      { left:'HCl',  right:'Hydrochloric acid' },
      { left:'H₂SO₄',right:'Sulfuric acid' },
      { left:'HNO₃', right:'Nitric acid' },
      { left:'CH₃COOH',right:'Acetic acid (Vinegar)' },
    ] },
  { id:'chem028', category:'chemistry', type:'match', difficulty:'medium', status:'active',
    text:'Match each reaction type to its correct description:',
    pairs:[
      { left:'Exothermic',   right:'Releases heat to surroundings' },
      { left:'Endothermic',  right:'Absorbs heat from surroundings' },
      { left:'Redox',        right:'Involves electron transfer' },
      { left:'Precipitation',right:'Forms insoluble solid from solution' },
    ] },
  { id:'chem029', category:'chemistry', type:'match', difficulty:'hard', status:'active',
    text:'Match each organic functional group to its class of compound:',
    pairs:[
      { left:'-OH',   right:'Alcohol' },
      { left:'-COOH', right:'Carboxylic acid' },
      { left:'-NH₂',  right:'Amine' },
      { left:'-CHO',  right:'Aldehyde' },
    ] },
  { id:'chem030', category:'chemistry', type:'match', difficulty:'medium', status:'active',
    text:'Match each gas with its test / identification method:',
    pairs:[
      { left:'Oxygen',         right:'Relights a glowing splint' },
      { left:'Hydrogen',       right:'Burns with a squeaky pop' },
      { left:'Carbon dioxide', right:'Turns limewater milky' },
      { left:'Chlorine',       right:'Bleaches damp litmus paper' },
    ] },
];

// ─── Default Physics Questions (30) ───────────────────────────────────────
export const DEFAULT_PHYSICS = [
  { id:'phys001', category:'physics', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the SI unit of force?',
    options:['Joule','Watt','Newton','Pascal'], correct:2,
    explanation:'Force is measured in Newtons (N), named after Sir Isaac Newton.' },
  { id:'phys002', category:'physics', type:'mcq', difficulty:'easy', status:'active',
    text:'Which law states: "For every action there is an equal and opposite reaction"?',
    options:["Newton's 1st Law","Newton's 2nd Law","Newton's 3rd Law","Hooke's Law"],
    correct:2, explanation:"Newton's Third Law describes action-reaction pairs between two bodies." },
  { id:'phys003', category:'physics', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the speed of light in a vacuum?',
    options:['3 × 10⁶ m/s','3 × 10⁸ m/s','3 × 10¹⁰ m/s','3 × 10⁵ m/s'], correct:1,
    explanation:'Light travels at approximately 3 × 10⁸ metres per second in a vacuum.' },
  { id:'phys004', category:'physics', type:'mcq', difficulty:'easy', status:'active',
    text:'What type of energy does a moving object possess?',
    options:['Potential energy','Chemical energy','Kinetic energy','Nuclear energy'], correct:2,
    explanation:'Kinetic energy is the energy an object has due to its motion: KE = ½mv².' },
  { id:'phys005', category:'physics', type:'mcq', difficulty:'easy', status:'active',
    text:'Ohm\'s Law relates which three electrical quantities?',
    options:['Power, current, time','Voltage, current, resistance','Charge, mass, velocity','Energy, frequency, wavelength'],
    correct:1, explanation:'Ohm\'s Law: V = IR (Voltage = Current × Resistance).' },
  { id:'phys006', category:'physics', type:'mcq', difficulty:'easy', status:'active',
    text:'What phenomenon causes a rainbow to form?',
    options:['Reflection of light','Refraction and dispersion of light through water droplets','Diffraction of light','Interference of light'],
    correct:1, explanation:'Rainbows form when light is refracted and dispersed into its spectrum by raindrops.' },
  { id:'phys007', category:'physics', type:'mcq', difficulty:'easy', status:'active',
    text:'The unit of electrical power is:',
    options:['Volt','Ampere','Ohm','Watt'], correct:3,
    explanation:'Power is measured in Watts (W). P = VI = I²R = V²/R.' },
  { id:'phys008', category:'physics', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the acceleration due to gravity on Earth\'s surface (approximately)?',
    options:['5 m/s²','9.8 m/s²','12 m/s²','15 m/s²'], correct:1,
    explanation:'Earth\'s gravitational acceleration is approximately g = 9.8 m/s² (often rounded to 10).' },
  { id:'phys009', category:'physics', type:'mcq', difficulty:'medium', status:'active',
    text:'Which equation correctly expresses kinetic energy?',
    options:['KE = mgh','KE = mv','KE = ½mv²','KE = Fd'], correct:2,
    explanation:'Kinetic energy formula: KE = ½mv² where m is mass and v is velocity.' },
  { id:'phys010', category:'physics', type:'mcq', difficulty:'medium', status:'active',
    text:'What does the second law of thermodynamics state about entropy?',
    options:['Entropy of an isolated system always decreases','Entropy remains constant in all processes','Entropy of an isolated system tends to increase over time','Entropy equals enthalpy minus temperature'],
    correct:2, explanation:'The second law states that entropy of an isolated system never decreases.' },
  { id:'phys011', category:'physics', type:'mcq', difficulty:'medium', status:'active',
    text:'Which phenomenon is responsible for the bending of light as it passes from air to glass?',
    options:['Reflection','Diffraction','Refraction','Polarisation'], correct:2,
    explanation:'Refraction occurs when light changes speed as it passes between media of different optical densities.' },
  { id:'phys012', category:'physics', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the relationship between frequency and wavelength of a wave?',
    options:['Directly proportional','No relationship','Inversely proportional','Exponentially proportional'],
    correct:2, explanation:'v = fλ. For constant wave speed, frequency and wavelength are inversely proportional.' },
  { id:'phys013', category:'physics', type:'mcq', difficulty:'medium', status:'active',
    text:'In a series circuit with two resistors R₁ and R₂, the total resistance is:',
    options:['R₁ × R₂','R₁ + R₂','(R₁ × R₂)/(R₁ + R₂)','R₁ - R₂'], correct:1,
    explanation:'In series circuits, resistances add: R_total = R₁ + R₂ + ...' },
  { id:'phys014', category:'physics', type:'mcq', difficulty:'medium', status:'active',
    text:'Which type of electromagnetic radiation has the shortest wavelength?',
    options:['Radio waves','Visible light','Ultraviolet','Gamma rays'], correct:3,
    explanation:'Gamma rays have the shortest wavelength (and highest energy) in the EM spectrum.' },
  { id:'phys015', category:'physics', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the work done when a 10N force moves an object 5m in the direction of the force?',
    options:['2 J','15 J','50 J','0.5 J'], correct:2,
    explanation:'W = F × d = 10 × 5 = 50 joules.' },
  { id:'phys016', category:'physics', type:'mcq', difficulty:'medium', status:'active',
    text:'The Doppler effect is the change in:',
    options:['Amplitude of waves due to source movement','Frequency of waves due to relative motion between source and observer','Speed of light in different media','Polarisation of electromagnetic waves'],
    correct:1, explanation:'The Doppler effect: frequency appears higher when source approaches, lower when receding.' },
  { id:'phys017', category:'physics', type:'mcq', difficulty:'medium', status:'active',
    text:'What does Archimedes\' principle state?',
    options:['Pressure increases with depth in a fluid','A floating object displaces its own weight of fluid','An object immersed in fluid experiences upthrust equal to the weight of fluid displaced','Fluid pressure acts equally in all directions'],
    correct:2, explanation:'Archimedes: upthrust = weight of displaced fluid, regardless of object material.' },
  { id:'phys018', category:'physics', type:'mcq', difficulty:'hard', status:'active',
    text:'According to Einstein\'s mass-energy equivalence, energy equals:',
    options:['mc','mc²','½mc²','2mc²'], correct:1,
    explanation:'E = mc² is Einstein\'s famous equation linking mass and energy through the speed of light squared.' },
  { id:'phys019', category:'physics', type:'mcq', difficulty:'hard', status:'active',
    text:'What is the de Broglie wavelength formula?',
    options:['λ = h/mv','λ = mv/h','λ = h × mv','λ = m/hv'], correct:0,
    explanation:'de Broglie: λ = h/p = h/(mv), where h is Planck\'s constant and p is momentum.' },
  { id:'phys020', category:'physics', type:'mcq', difficulty:'hard', status:'active',
    text:'Heisenberg\'s uncertainty principle states that we cannot simultaneously know:',
    options:['Mass and charge of a particle','Position and momentum precisely','Spin and charge of an electron','Energy and wavelength of a photon'],
    correct:1, explanation:'ΔxΔp ≥ ħ/2: the more precisely we know position, the less precisely we can know momentum.' },
  { id:'phys021', category:'physics', type:'mcq', difficulty:'hard', status:'active',
    text:'In nuclear fission, a heavy nucleus splits into lighter nuclei and releases energy because:',
    options:['Chemical bonds are broken','The binding energy per nucleon increases','Temperature increases','Electrons are emitted'],
    correct:1, explanation:'Fission releases energy because products have higher binding energy per nucleon than the parent.' },
  { id:'phys022', category:'physics', type:'mcq', difficulty:'hard', status:'active',
    text:'Which equation describes the photoelectric effect threshold?',
    options:['E = hf - φ (work function)','E = mc²','E = qV','F = ma'],
    correct:0, explanation:'Maximum KE of emitted electrons = hf - φ, where φ is the work function of the material.' },
  { id:'phys023', category:'physics', type:'mcq', difficulty:'hard', status:'active',
    text:'Gravitational potential energy at height h above Earth\'s surface is:',
    options:['mgh (near surface)','½mv²','mc²','F/A'], correct:0,
    explanation:'GPE = mgh near Earth\'s surface, where g = 9.8 m/s² and h is height above reference point.' },
  { id:'phys024', category:'physics', type:'mcq', difficulty:'hard', status:'active',
    text:'What is the period of a simple pendulum of length L?',
    options:['T = 2π√(g/L)','T = 2π√(L/g)','T = π√(L/g)','T = √(2πL/g)'],
    correct:1, explanation:'T = 2π√(L/g). Period increases with length and is independent of amplitude (for small angles).' },
  { id:'phys025', category:'physics', type:'mcq', difficulty:'hard', status:'active',
    text:'Faraday\'s law of electromagnetic induction states that induced EMF is proportional to:',
    options:['Current in the conductor','Rate of change of magnetic flux','Resistance of the circuit','Charge stored in the capacitor'],
    correct:1, explanation:'EMF = -dΦ/dt. The induced voltage equals the rate of change of magnetic flux.' },
  { id:'phys026', category:'physics', type:'match', difficulty:'easy', status:'active',
    text:'Match each physical quantity to its SI unit:',
    pairs:[
      { left:'Force',     right:'Newton (N)' },
      { left:'Energy',    right:'Joule (J)' },
      { left:'Power',     right:'Watt (W)' },
      { left:'Pressure',  right:'Pascal (Pa)' },
    ] },
  { id:'phys027', category:'physics', type:'match', difficulty:'medium', status:'active',
    text:"Match each of Newton's Laws to its description:",
    pairs:[
      { left:'First Law',  right:'Object stays at rest or uniform motion unless acted upon' },
      { left:'Second Law', right:'F = ma (force equals mass times acceleration)' },
      { left:'Third Law',  right:'Every action has an equal and opposite reaction' },
      { left:'Law of Gravitation', right:'F = Gm₁m₂/r² (attraction between masses)' },
    ] },
  { id:'phys028', category:'physics', type:'match', difficulty:'medium', status:'active',
    text:'Match each type of electromagnetic wave to its primary application:',
    pairs:[
      { left:'Radio waves',  right:'Broadcasting / communication' },
      { left:'X-rays',       right:'Medical imaging' },
      { left:'Infrared',     right:'Thermal imaging / remote controls' },
      { left:'Gamma rays',   right:'Cancer radiotherapy' },
    ] },
  { id:'phys029', category:'physics', type:'match', difficulty:'hard', status:'active',
    text:'Match each scientist to their major contribution in physics:',
    pairs:[
      { left:'Einstein',  right:'Mass-energy equivalence (E=mc²)' },
      { left:'Faraday',   right:'Electromagnetic induction' },
      { left:'Bohr',      right:'Atomic model with electron orbits' },
      { left:'Heisenberg',right:'Uncertainty principle' },
    ] },
  { id:'phys030', category:'physics', type:'match', difficulty:'medium', status:'active',
    text:'Match each wave property to its correct definition:',
    pairs:[
      { left:'Amplitude',  right:'Maximum displacement from equilibrium' },
      { left:'Frequency',  right:'Number of complete cycles per second' },
      { left:'Wavelength', right:'Distance between two successive crests' },
      { left:'Period',     right:'Time for one complete cycle' },
    ] },
];

// ─── Default Mathematics Questions (30) ───────────────────────────────────
export const DEFAULT_MATHEMATICS = [
  { id:'math001', category:'mathematics', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the value of 2³ × 4?',
    options:['16','24','32','48'], correct:2,
    explanation:'2³ = 8. 8 × 4 = 32.' },
  { id:'math002', category:'mathematics', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the square root of 144?',
    options:['11','12','13','14'], correct:1,
    explanation:'√144 = 12, because 12 × 12 = 144.' },
  { id:'math003', category:'mathematics', type:'mcq', difficulty:'easy', status:'active',
    text:'Which of the following is a prime number?',
    options:['9','15','17','21'], correct:2,
    explanation:'17 is divisible only by 1 and itself. 9=3², 15=3×5, 21=3×7.' },
  { id:'math004', category:'mathematics', type:'mcq', difficulty:'easy', status:'active',
    text:'What is 15% of 200?',
    options:['20','25','30','35'], correct:2,
    explanation:'15% of 200 = (15/100) × 200 = 30.' },
  { id:'math005', category:'mathematics', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the perimeter of a rectangle with length 8 cm and width 5 cm?',
    options:['13 cm','26 cm','40 cm','20 cm'], correct:1,
    explanation:'Perimeter = 2(l + w) = 2(8 + 5) = 2 × 13 = 26 cm.' },
  { id:'math006', category:'mathematics', type:'mcq', difficulty:'easy', status:'active',
    text:'Solve: 3x + 6 = 21. What is x?',
    options:['3','4','5','9'], correct:2,
    explanation:'3x = 21 - 6 = 15. x = 15/3 = 5.' },
  { id:'math007', category:'mathematics', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the area of a circle with radius 7 cm? (Use π ≈ 22/7)',
    options:['44 cm²','154 cm²','78 cm²','22 cm²'], correct:1,
    explanation:'Area = πr² = (22/7) × 7² = (22/7) × 49 = 154 cm².' },
  { id:'math008', category:'mathematics', type:'mcq', difficulty:'easy', status:'active',
    text:'What is the LCM of 4 and 6?',
    options:['2','8','12','24'], correct:2,
    explanation:'LCM(4,6) = 12 (smallest number divisible by both 4 and 6).' },
  { id:'math009', category:'mathematics', type:'mcq', difficulty:'medium', status:'active',
    text:'If sin θ = 3/5, what is cos θ (assuming θ is in the first quadrant)?',
    options:['4/5','3/4','5/3','5/4'], correct:0,
    explanation:'sin²θ + cos²θ = 1. cos²θ = 1 - 9/25 = 16/25. cos θ = 4/5.' },
  { id:'math010', category:'mathematics', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the sum of the interior angles of a hexagon?',
    options:['540°','720°','900°','360°'], correct:1,
    explanation:'Sum of interior angles = (n-2) × 180°. For n=6: (6-2) × 180° = 720°.' },
  { id:'math011', category:'mathematics', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the value of log₁₀(1000)?',
    options:['2','3','4','10'], correct:1,
    explanation:'log₁₀(1000) = log₁₀(10³) = 3.' },
  { id:'math012', category:'mathematics', type:'mcq', difficulty:'medium', status:'active',
    text:'The quadratic equation x² - 5x + 6 = 0 has roots:',
    options:['x = 1, x = 6','x = 2, x = 3','x = -2, x = -3','x = 2, x = -3'],
    correct:1, explanation:'Factoring: (x-2)(x-3) = 0 → x = 2 or x = 3.' },
  { id:'math013', category:'mathematics', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the slope of the line passing through points (2, 3) and (6, 11)?',
    options:['1','2','3','4'], correct:1,
    explanation:'Slope = (y₂-y₁)/(x₂-x₁) = (11-3)/(6-2) = 8/4 = 2.' },
  { id:'math014', category:'mathematics', type:'mcq', difficulty:'medium', status:'active',
    text:'In an arithmetic progression, the first term is 5 and common difference is 3. What is the 10th term?',
    options:['30','32','35','38'], correct:1,
    explanation:'aₙ = a₁ + (n-1)d = 5 + (10-1)×3 = 5 + 27 = 32.' },
  { id:'math015', category:'mathematics', type:'mcq', difficulty:'medium', status:'active',
    text:'What is the probability of rolling a sum of 7 with two dice?',
    options:['1/6','5/36','6/36','7/36'], correct:2,
    explanation:'Combinations giving 7: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) = 6 outcomes. P = 6/36 = 1/6.' },
  { id:'math016', category:'mathematics', type:'mcq', difficulty:'medium', status:'active',
    text:'The volume of a sphere with radius r is:',
    options:['(4/3)πr²','(4/3)πr³','4πr²','(2/3)πr³'], correct:1,
    explanation:'Volume of sphere = (4/3)πr³.' },
  { id:'math017', category:'mathematics', type:'mcq', difficulty:'medium', status:'active',
    text:'Simplify: (2x³y²)(3x²y) =',
    options:['5x⁵y³','6x⁵y³','6x⁶y²','5x⁶y³'], correct:1,
    explanation:'Multiply coefficients: 2×3=6. Add exponents: x³⁺²=x⁵, y²⁺¹=y³. Answer: 6x⁵y³.' },
  { id:'math018', category:'mathematics', type:'mcq', difficulty:'hard', status:'active',
    text:'What is the derivative of f(x) = x³ - 3x² + 2x?',
    options:['3x² - 3x + 2','3x² - 6x + 2','x² - 6x + 2','3x² - 6x'],
    correct:1, explanation:'d/dx(x³) = 3x², d/dx(-3x²) = -6x, d/dx(2x) = 2. So f\'(x) = 3x² - 6x + 2.' },
  { id:'math019', category:'mathematics', type:'mcq', difficulty:'hard', status:'active',
    text:'Evaluate: ∫₀² (2x + 1) dx',
    options:['4','5','6','8'], correct:2,
    explanation:'∫(2x+1)dx = x² + x. From 0 to 2: (4+2) - (0+0) = 6.' },
  { id:'math020', category:'mathematics', type:'mcq', difficulty:'hard', status:'active',
    text:'The determinant of the matrix [[3,1],[2,4]] is:',
    options:['8','10','14','2'], correct:1,
    explanation:'det = (3×4) - (1×2) = 12 - 2 = 10.' },
  { id:'math021', category:'mathematics', type:'mcq', difficulty:'hard', status:'active',
    text:'How many ways can 5 people be arranged in a row?',
    options:['25','60','120','720'], correct:2,
    explanation:'5! = 5 × 4 × 3 × 2 × 1 = 120 permutations.' },
  { id:'math022', category:'mathematics', type:'mcq', difficulty:'hard', status:'active',
    text:'The sum of the infinite geometric series 1 + 1/2 + 1/4 + ... is:',
    options:['1.5','2','2.5','3'], correct:1,
    explanation:'S = a/(1-r) = 1/(1-0.5) = 1/0.5 = 2.' },
  { id:'math023', category:'mathematics', type:'mcq', difficulty:'hard', status:'active',
    text:'What is the equation of a circle with centre (3, -2) and radius 5?',
    options:['(x-3)²+(y+2)²=25','(x+3)²+(y-2)²=25','(x-3)²+(y-2)²=25','(x+3)²+(y+2)²=5'],
    correct:0, explanation:'Standard form: (x-h)²+(y-k)²=r². With (h,k)=(3,-2) and r=5: (x-3)²+(y+2)²=25.' },
  { id:'math024', category:'mathematics', type:'mcq', difficulty:'hard', status:'active',
    text:'Using Bayes\' theorem, if P(A)=0.3, P(B|A)=0.6, P(B|A\')=0.2, what is P(A|B)?',
    options:['0.39','0.56','0.45','0.30'], correct:1,
    explanation:'P(B)=0.3×0.6+0.7×0.2=0.18+0.14=0.32. P(A|B)=0.18/0.32=0.5625≈0.56.' },
  { id:'math025', category:'mathematics', type:'mcq', difficulty:'hard', status:'active',
    text:'Which conic section is represented by x²/16 + y²/9 = 1?',
    options:['Circle','Ellipse','Parabola','Hyperbola'], correct:1,
    explanation:'When a²≠b² in x²/a²+y²/b²=1, the curve is an ellipse.' },
  { id:'math026', category:'mathematics', type:'match', difficulty:'easy', status:'active',
    text:'Match each shape to its correct area formula:',
    pairs:[
      { left:'Rectangle',   right:'l × w' },
      { left:'Triangle',    right:'½ × b × h' },
      { left:'Circle',      right:'πr²' },
      { left:'Trapezoid',   right:'½(a+b)×h' },
    ] },
  { id:'math027', category:'mathematics', type:'match', difficulty:'medium', status:'active',
    text:'Match each trigonometric ratio to its definition:',
    pairs:[
      { left:'sin θ', right:'Opposite / Hypotenuse' },
      { left:'cos θ', right:'Adjacent / Hypotenuse' },
      { left:'tan θ', right:'Opposite / Adjacent' },
      { left:'cosec θ',right:'Hypotenuse / Opposite' },
    ] },
  { id:'math028', category:'mathematics', type:'match', difficulty:'medium', status:'active',
    text:'Match each sequence type to its defining property:',
    pairs:[
      { left:'Arithmetic Progression', right:'Constant difference between terms' },
      { left:'Geometric Progression',  right:'Constant ratio between terms' },
      { left:'Fibonacci Sequence',     right:'Each term is sum of two preceding terms' },
      { left:'Harmonic Progression',   right:'Reciprocals form an arithmetic progression' },
    ] },
  { id:'math029', category:'mathematics', type:'match', difficulty:'hard', status:'active',
    text:'Match each calculus concept to its description:',
    pairs:[
      { left:'Derivative',    right:'Rate of change of a function' },
      { left:'Integral',      right:'Area under a curve' },
      { left:'Limit',         right:'Value a function approaches as input approaches a point' },
      { left:'Chain Rule',    right:'Differentiating composite functions' },
    ] },
  { id:'math030', category:'mathematics', type:'match', difficulty:'easy', status:'active',
    text:'Match each mathematical term to its definition:',
    pairs:[
      { left:'Prime number',    right:'Divisible only by 1 and itself' },
      { left:'Factor',          right:'Number that divides another exactly' },
      { left:'LCM',             right:'Smallest common multiple of two numbers' },
      { left:'HCF',             right:'Largest common factor of two numbers' },
    ] },
];

// ─── Utilities ─────────────────────────────────────────────────────────────

const DEFAULTS = {
  robotics:    DEFAULT_ROBOTICS,
  chemistry:   DEFAULT_CHEMISTRY,
  physics:     DEFAULT_PHYSICS,
  mathematics: DEFAULT_MATHEMATICS,
};

export const CATEGORIES = ['robotics', 'chemistry', 'physics', 'mathematics'];

export const CATEGORY_META = {
  robotics:    { label: 'Robotics',    color: '#3BC0EF', bg: '#eff9fd' },
  chemistry:   { label: 'Chemistry',   color: '#10B981', bg: '#f0fdf4' },
  physics:     { label: 'Physics',     color: '#F59E0B', bg: '#fffbeb' },
  mathematics: { label: 'Mathematics', color: '#8B5CF6', bg: '#f5f3ff' },
};

export function loadQuestionBank() {
  try {
    const stored = JSON.parse(localStorage.getItem(QB_KEY) || '{}');
    const result = {};
    CATEGORIES.forEach(cat => {
      result[cat] = Array.isArray(stored[cat]) && stored[cat].length > 0
        ? stored[cat]
        : DEFAULTS[cat].map(q => ({ ...q }));
    });
    return result;
  } catch {
    const result = {};
    CATEGORIES.forEach(cat => { result[cat] = DEFAULTS[cat].map(q => ({ ...q })); });
    return result;
  }
}

export function saveQuestionBank(bank) {
  try { localStorage.setItem(QB_KEY, JSON.stringify(bank)); } catch {}
}

export function ensureQuestionBankSeeded() {
  try {
    const stored = JSON.parse(localStorage.getItem(QB_KEY) || '{}');
    let changed = false;
    CATEGORIES.forEach(cat => {
      if (!Array.isArray(stored[cat]) || stored[cat].length === 0) {
        stored[cat] = DEFAULTS[cat].map(q => ({ ...q }));
        changed = true;
      }
    });
    if (changed) localStorage.setItem(QB_KEY, JSON.stringify(stored));
  } catch {}
}

export function getCategoryQuestions(category) {
  const bank = loadQuestionBank();
  return (bank[category] || []).filter(q => q.status === 'active');
}

export function getAllActiveQuestions() {
  const bank = loadQuestionBank();
  return CATEGORIES.flatMap(cat => (bank[cat] || []).filter(q => q.status === 'active'));
}

export function saveCategoryQuestions(category, questions) {
  const bank = loadQuestionBank();
  bank[category] = questions;
  saveQuestionBank(bank);
}

export function addQuestion(question) {
  const bank = loadQuestionBank();
  const cat = question.category;
  if (!bank[cat]) bank[cat] = [];
  bank[cat].push(question);
  saveQuestionBank(bank);
}

export function updateQuestion(question) {
  const bank = loadQuestionBank();
  const cat = question.category;
  bank[cat] = (bank[cat] || []).map(q => q.id === question.id ? question : q);
  saveQuestionBank(bank);
}

export function deleteQuestion(category, questionId) {
  const bank = loadQuestionBank();
  bank[category] = (bank[category] || []).filter(q => q.id !== questionId);
  saveQuestionBank(bank);
}

export function generateQuestionId(category) {
  const prefix = { robotics:'rob', chemistry:'chem', physics:'phys', mathematics:'math' }[category] || 'q';
  return `${prefix}${Date.now()}`;
}
